name: Snif strict type
on: [push]
jobs:
  StrictType:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nvv-app
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2

      - name: Composer Cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-dev-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-dev-${{ hashFiles('composer.lock') }}
            composer-dev-
      - name: Composer Install Dev
        run: |
          composer install
      - name: Sniffer job
        run: |
          composer check-style
          composer fix-style